org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn
net.minecraftforge.gradle.merge-source-sets=true
org.gradle.java.installations.paths=F:/_a/WELLS_HRToytoolbox/mod/mc/.gradle/caches/minecraftforge/forgegradle/mavenizer/caches/microsoft-jdk-21.0.12-windows-x64