modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

# Client-only: skip dedicated server load.
# Docs: https://docs.minecraftforge.net/en/1.20.1/concepts/sides/
clientSideOnly=true

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
displayTest="IGNORE_ALL_VERSION"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="CLIENT"
